[boris]
  version = 1

[build.submodules]
  git = "refs/heads/**"

[build.validate]
  git = "refs/heads/master"

[build.all-*]
  git = "refs/heads/**"

[build.dist-*]
  git = "refs/heads/master"

[build.branches-*]
  git = "refs/heads/topic/*"
