[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/latest/master-haskell-latest"
  version = 1

[global]
  CABAL_VERSION = "1.24.0.2"
  CACHE = "true"

[build.dist-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"

[build.dist-8-0]
  GHC_VERSION = "8.0.2"
  CABAL_VERSION = "1.24.0.0"

[build.branches-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"

[build.branches-8-0]
  GHC_VERSION = "8.0.2"
  CABAL_VERSION = "1.24.0.0"

[build.dist-8-2]
  GHC_VERSION = "8.2.2"
  CABAL_VERSION = "2.0.0.1"

[build.branches-8-2]
  GHC_VERSION = "8.2.2"
  CABAL_VERSION = "2.0.0.1"
